name: Test and Lint

on:
  workflow_call:

jobs:
  python:
    name: Python
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Python flake8
        run: docker compose run --rm app sh -c "flake8"
